name: Test
on: [pull_request, workflow_dispatch]
jobs:
  test:
    container: ubuntu:latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install test dependencies
      run: apt-get update && apt-get install -y build-essential check